(function () {
  var T = {
    it: {
      // shared
      'nav.home': 'Inizio',
      'nav.overview': 'Panoramica',
      'nav.infolayer': 'Layer informativo',
      'btn.view': 'Visualizza',
      'btn.open': 'Apri',
      'gis.title': 'Fonti dati GIS',
      'gis.intro': 'Le fonti riportate fanno riferimento ai dataset utilizzati per la costruzione del layer e sono indicate con il relativo anno di riferimento e regime di licenza, ove disponibile.',
      'th.name': 'Nome dataset',
      'th.year': 'Anno di riferimento',
      'th.source': 'Fonte',
      'th.license': 'Licenza',
      'th.link': 'Link',
      'common.to_complete': 'Da completare',

      // index.html
      'idx.nav.numbers': 'Figure',
      'idx.nav.features': 'Esplora i layer',
      'idx.nav.partners': 'Partner',
      'idx.nav.overview': 'Panoramica',
      'idx.kicker': 'Piattaforma WebGIS',
      'idx.h1': 'MOR – Piattaforma WebGIS del Mercato Ortofrutticolo del Roero',
      'idx.lead': 'Uno strumento di analisi e visualizzazione territoriale a supporto della filiera agroalimentare del Roero.',
      'idx.support': 'La piattaforma MOR raccoglie e organizza in ambiente WebGIS i principali dati territoriali. L\'applicativo consente di esplorare, in modo semplice e integrato, le dinamiche della filiera ortofrutticola, i collegamenti con il sistema turistico locale e la localizzazione di terreni e coltivi per analisi territoriali.',
      'idx.btn.explore': 'Esplora i layer',
      'idx.btn.learn': 'Approfondisci la piattaforma',
      'idx.numeri.title': 'Il Mercato chiuso del MOR in numeri',
      'idx.numeri.intro': 'Sezione infografica dedicata a una lettura sintetica del mercato chiuso, mantenendo il contenuto visuale fornito e integrandolo nella nuova identità grafica del portale.',
      'idx.features.title': 'I layer informativi della piattaforma',
      'idx.features.intro': 'La piattaforma è organizzata in layer tematici che rappresentano dataset territoriali. Ogni layer consente una lettura specifica del sistema locale e contribuisce a una visione d\'insieme del Mercato Ortofrutticolo del Roero.',
      'idx.card.photo.title': 'Layer agrifotovoltaico',
      'idx.card.photo.desc': 'Mappatura di terreni disponibili per analisi territoriali legate alla localizzazione di impianti fotovoltaici.',
      'idx.card.od.title': 'Layer origine-destinazione',
      'idx.card.od.desc': 'Visualizzazione dei flussi storici dei prodotti ortofrutticoli tra comuni, organizzati per origine e destinazione.',
      'idx.card.tourism.title': 'Layer turistico',
      'idx.card.tourism.desc': 'Individuazione delle aree in cui la filiera agricola si interseca con le filiere turistiche del territorio.',
      'idx.note': 'In questa revisione sono stati rimossi i riferimenti alla sezione contatti, in coerenza con le annotazioni presenti nel PDF delle modifiche ai contenuti.',

      // partners.html
      'par.breadcrumb': 'Home / Partner',
      'par.kicker': 'I nostri partner',
      'par.title': 'In collaborazione con il Politecnico di Torino',

      // explore-MOR.html
      'exp.nav.numbers': 'Numeri',
      'exp.nav.features': 'Layer',
      'exp.breadcrumb': 'Home / Panoramica',
      'exp.kicker': 'Panoramica del progetto',
      'exp.h1': 'MOR: una piattaforma GIS per leggere il territorio',
      'exp.lead': 'La piattaforma MOR è un applicativo WebGIS pilota sviluppato per integrare e visualizzare dati territoriali rilevanti per il sistema agroalimentare del Roero.',
      'exp.support': 'Il portale non ha finalità valutative o autorizzative, ma consente di consultare in forma georeferenziata dataset utili all\'analisi della filiera, della logistica e delle relazioni con il contesto territoriale.',
      'exp.p1': 'Attraverso la consultazione dei layer è possibile osservare i flussi origine-destinazione nel mercato chiuso dei prodotti ortofrutticoli, secondo censimento del 2026. È inoltre rappresentata l\'intersezione con aree e percorsi turistici. In lettura con apposita autorizzazione, è possibile visualizzare i fattori di esclusione e di idoneità relativi all\'installazione di pannelli agrifotovoltaici.',
      'exp.p2': 'La piattaforma è quindi uno strumento di lettura territoriale: raccoglie informazioni eterogenee, le rende navigabili su base geografica e permette una consultazione sintetica ma strutturata dei risultati prodotti dal progetto.',
      'exp.layers.title': 'Layer disponibili',
      'exp.card.photo.title': 'Agrifotovoltaico',
      'exp.card.photo.desc': 'Mappatura territoriale di terreni censiti per analisi localizzative.',
      'exp.card.od.title': 'Origine-destinazione',
      'exp.card.od.desc': 'Visualizzazione dei flussi storici dei prodotti ortofrutticoli.',
      'exp.card.tourism.title': 'Filiere turistiche',
      'exp.card.tourism.desc': 'Aree di intersezione tra sistema agricolo e sistema turistico.',

      // photovoltaic.html
      'pho.breadcrumb': 'Home / Layer / Agrifotovoltaico',
      'pho.h1': 'Layer agrifotovoltaico',
      'pho.lead': 'Mappatura territoriale di terreni censiti per analisi localizzative.',
      'pho.support': 'Questo layer raccoglie e visualizza i dati geografici relativi agli elementi considerati nel progetto per analisi territoriali connesse al fotovoltaico.',
      'pho.btn.map': '&#128506; Apri Mappa Fotovoltaico',
      'pho.p1': 'La consultazione consente di localizzare gli elementi censiti e leggerli nel contesto spaziale del Roero, senza entrare in valutazioni economiche, progettuali o autorizzative.',
      'pho.p2': 'Il layer è stato sviluppato come componente informativa e costituisce una base cartografica utile per successive analisi. La resa finale del WebGIS può essere affiancata da un breve paragrafo metodologico che descriva i criteri di selezione, gli attributi visualizzati e l\'eventuale distinzione tra terreni, coltivi ed elementi soggetti a vincoli.',
      'pho.note': '<strong>Da completare:</strong> la sezione descrittiva di dati e metodologia può essere raffinata appena hai l\'elenco definitivo dei campi effettivamente pubblicati nella mappa.',

      // tourism.html
      'tou.btn.map': '&#128506; Apri Mappa Turismo',
      'tou.breadcrumb': 'Home / Layer / Filiere turistiche',
      'tou.h1': 'Layer filiere turistiche',
      'tou.lead': 'Aree di intersezione tra sistema agricolo e sistema turistico.',
      'tou.support': 'Questo layer visualizza l\'incrocio tra i dati della filiera agricola e le eventuali filiere turistiche presenti sul territorio.',
      'tou.p1': 'L\'obiettivo è restituire una lettura spaziale delle aree in cui produzione agricola, servizi e attrattività territoriale si sovrappongono o interagiscono.',
      'tou.p2': 'Il layer ha una funzione informativa e conoscitiva: permette di osservare la distribuzione territoriale dei dati e supporta una lettura integrata del contesto locale all\'interno della piattaforma WebGIS.',
      'tou.p3': 'Il Roero è inserito tra i siti di Patrimonio Mondiale UNESCO per i suoi paesaggi vitivinicoli. Il contenuto del layer turistico è riferito ai comuni del Roero e ai percorsi "WineTour tra i cru del Roero", nati dalla collaborazione tra il Consorzio di Tutela Roero e l\'Ecomuseo delle Rocche del Roero. SitoWeb: https://www.consorziodelroero.it/i-winetour-tra-i-cru-del-roero/',
      'tou.data.winetour': 'WineTour tra i cru del Roero',
      'tou.data.comuni': 'Comuni del Roero',
      'tou.data.consorzio': 'Consorzio di Tutela Roero / Ecomuseo delle Rocche del Roero',

      // origin-destination.html
      'od.breadcrumb': 'Home / Layer / Origine-destinazione',
      'od.h1': 'Layer origine-destinazione',
      'od.lead': 'Visualizzazione dei flussi storici dei prodotti ortofrutticoli.',
      'od.support': 'Questo layer rappresenta la matrice origine-destinazione dei prodotti ortofrutticoli, costruita a partire dai dati storici disponibili.',
      'od.btn.method': '&#8595; Metodologia',
      'od.btn.gis': '&#8595; Fonti dati GIS',
      'od.btn.map': '&#128506; Apri Mappa Flussi OD',
      'od.p1': 'La visualizzazione consente di leggere i collegamenti tra i territori di provenienza e quelli di destinazione dei flussi, offrendo una rappresentazione sintetica e animata delle relazioni logistiche della filiera.',
      'od.p2': 'Il layer è stato sviluppato come strumento di visualizzazione infografica, utile per interpretare l\'organizzazione spaziale dei movimenti dei prodotti nel sistema chiuso del Mercato Ortofrutticolo del Roero. I dati proposti sono derivati dal censimento realizzato nel 2026.',
      'od.p3': 'Ogni record di flusso collega un comune di origine, dove il prodotto è stato raccolto, al MOR. I record sono datati e categorizzati per tipo di prodotto e produttore.',
      'od.method.title': 'Metodologia',
      'od.method.p1': 'Per analizzare la distribuzione spaziale dei flussi di approvvigionamento all\'interno del sistema del Mercato Ortofrutticolo del Roero, è stata costruita una matrice origine-destinazione (OD) per quantificare le relazioni logistiche tra i produttori e il Mercato Ortofrutticolo della Roero (MOR). Il primo passo ha riguardato la georeferenziazione della localizzazione di ciascun produttore nell\'area di studio, utilizzando dati di coordinate per posizionare accuratamente ogni nodo di approvvigionamento sulla mappa.',
      'od.method.p2': 'Sia le localizzazioni dei produttori che la rete stradale sono state proiettate in un sistema di riferimento comune WGS 84 / UTM Zona 32N (EPSG:32632), garantendo coerenza geometrica e precisione metrica in tutti gli strati spaziali utilizzati nell\'analisi. La rete stradale che copre l\'area di studio è stata successivamente integrata nel modello spaziale, servendo come base per il calcolo dei percorsi tra tutti i nodi identificati.',
      'od.method.p3': 'Utilizzando il software QGIS, la matrice OD è stata calcolata per due insiemi di relazioni: connessioni produttore-produttore e connessioni produttore-MOR. Per ogni coppia origine-destinazione, è stato calcolato il percorso stradale più breve e valutato in termini di distanza (km) e costo di trasporto stimato per chilometro, producendo una matrice costo-distanza completa. I valori risultanti sono riportati nella tabella sottostante.',
      'od.method.p4': 'Per supportare l\'interpretazione di questi flussi spaziali, è stata sviluppata una visualizzazione cartografica animata. Il movimento di ciascun produttore è rappresentato come un flusso dinamico sulla mappa, con etichette pop-up interattive che mostrano la distanza associata a ciascun percorso specifico. Questa rappresentazione animata migliora la leggibilità degli output della matrice OD, consentendo agli utenti di tracciare intuitivamente l\'organizzazione spaziale dei movimenti di prodotti e di valutare il relativo sforzo logistico coinvolto in ciascuna relazione di approvvigionamento.',
      'od.method.p5': 'Ogni record di flusso collega un comune di origine, dove il prodotto è stato raccolto, al MOR. I record sono datati e categorizzati per tipo di prodotto e produttore.',
      'od.data.census': 'Censimento mercato chiuso MOR',
      'od.data.road': 'Rete stradale',
      'od.data.study': 'Area di studio',

      // webgis-tourism
      'gis.tou.filter.title': 'Filtro Layer',
      'gis.tou.filter.hint': 'Clicca una sezione per attivare i layer',
      'gis.tou.study': 'Area di Studio',
      'gis.tou.tracks': 'WineTour tra i cru del Roero',
      'gis.tou.market.group': 'Localizzazione Mercato',
      'gis.tou.roero': 'Comuni del Roero',
      'gis.tou.cuneo': 'Provincia di Cuneo',
      'gis.tou.asti': 'Provincia di Asti',
      'gis.tou.alessandria': 'Provincia di Alessandria',
      'gis.tou.regione': 'Regione Piemonte',
      'gis.tou.track4': 'Percorso 4',
      'gis.tou.track3': 'Percorso 3',
      'gis.tou.track2': 'Percorso 2',
      'gis.tou.track1': 'Percorso 1',
      'gis.tou.market.name': 'Mercato Ortofrutticolo del Roero',
      'gis.tou.back': '&#8592; Indietro',
      'gis.tou.legend.title': 'Legenda',
      'gis.tou.legend.empty': 'Seleziona un gruppo di layer sulla sinistra per vedere la legenda.',

      // webgis-od
      'gis.od.filter.title': 'Filtro Layer',
      'gis.od.filter.hint': 'Clicca una sezione per attivare i layer',
      'gis.od.study': 'Area di Studio',
      'gis.od.flows': 'Flussi Origine-Destinazione',
      'gis.od.localities': 'Localizzazioni',
      'gis.od.roero': 'Comuni del Roero',
      'gis.od.cuneo': 'Provincia di Cuneo',
      'gis.od.asti': 'Provincia di Asti',
      'gis.od.alessandria': 'Provincia di Alessandria',
      'gis.od.regione': 'Regione Piemonte',
      'gis.od.3pl': '3PL MOR',
      'gis.od.p1': 'Pomodoro Cerrato d\'Asti',
      'gis.od.p2': 'Nocciole',
      'gis.od.p3': 'Melanzane',
      'gis.od.p4': 'Peperoni',
      'gis.od.p5': 'Pesche Tradizionali',
      'gis.od.p6': 'Fave',
      'gis.od.p7': 'Pere Madernassa',
      'gis.od.p8': 'Susine Dalmazzine',
      'gis.od.p9': 'Uva Fragola',
      'gis.od.p10': 'Uva Rossa Fresca',
      'gis.od.p11': 'Pere',
      'gis.od.p12': 'Fagioli Borlotti',
      'gis.od.p13': 'Materna Pere',
      'gis.od.localit': 'Località Matrice OD',
      'gis.od.back': '&#8592; Indietro',
      'gis.od.legend.title': 'Legenda',
      'gis.od.legend.empty': 'Seleziona un gruppo di layer sulla sinistra per vedere la legenda.',

      // webgis-photovoltaic
      'gis.photo.filter.title': 'Filtro Layer',
      'gis.photo.filter.hint': 'Clicca una sezione per attivare i layer',
      'gis.photo.study': 'Area di Studio',
      'gis.photo.market.group': 'Posizione del Mercato',
      'gis.photo.exclusion.group': 'Fattori di Esclusione',
      'gis.photo.photo.group': 'Idoneità Fotovoltaica',
      'gis.photo.catasto.group': 'Catasto',
      'gis.photo.lcp.group': 'Copertura del Suolo',
      'gis.photo.roero': 'Comuni del Roero',
      'gis.photo.cuneo': 'Provincia di Cuneo',
      'gis.photo.asti': 'Provincia di Asti',
      'gis.photo.alessandria': 'Provincia di Alessandria',
      'gis.photo.regione': 'Regione Piemonte',
      'gis.photo.market.name': 'Mercato Ortofrutticolo del Roero',
      'gis.photo.natura': 'Rete Natura 2000',
      'gis.photo.aree': 'Aree Protette (EUAP)',
      'gis.photo.frana': 'Pericolosità da Frana Elevata',
      'gis.photo.idraulica': 'Pericolosità Idraulica Elevata',
      'gis.photo.corpi': 'Corpi Idrici con Buffer',
      'gis.photo.stradale': 'Rete Stradale',
      'gis.photo.ferroviaria': 'Rete Ferroviaria',
      'gis.photo.slope': 'Analisi della Pendenza',
      'gis.photo.aspect': "Analisi dell'Esposizione",
      'gis.photo.catasto.layer': 'Originali di Impianto',
      'gis.photo.lcp.layer': 'Copertura del Suolo Piemonte 2021',
      'gis.photo.suit.none': 'Non adatto',
      'gis.photo.suit.vlow': 'Idoneità molto bassa',
      'gis.photo.suit.low': 'Idoneità bassa',
      'gis.photo.suit.mod': 'Idoneità moderata',
      'gis.photo.suit.high': 'Idoneità elevata',
      'gis.photo.suit.vhigh': 'Idoneità molto elevata',
      'gis.photo.back': '&#8592; Indietro',
      'gis.photo.legend.title': 'Legenda',
      'gis.photo.legend.empty': 'Seleziona un gruppo di layer sulla sinistra per vedere la legenda.',
    },

    en: {
      // shared
      'nav.home': 'Home',
      'nav.overview': 'Overview',
      'nav.infolayer': 'Information Layer',
      'btn.view': 'View',
      'btn.open': 'Open',
      'gis.title': 'GIS Data Sources',
      'gis.intro': 'The sources listed refer to the datasets used to build the layer and are indicated with their reference year and license, where available.',
      'th.name': 'Dataset name',
      'th.year': 'Reference year',
      'th.source': 'Source',
      'th.license': 'License',
      'th.link': 'Link',
      'common.to_complete': 'To be completed',

      // index.html
      'idx.nav.numbers': 'Figures',
      'idx.nav.features': 'Explore Layers',
      'idx.nav.partners': 'Partners',
      'idx.nav.overview': 'Overview',
      'idx.kicker': 'WebGIS Platform',
      'idx.h1': 'MOR – WebGIS Platform for the Roero Fruit and Vegetable Market',
      'idx.lead': 'A territorial analysis and visualization tool supporting the Roero agri-food supply chain.',
      'idx.support': 'The MOR platform collects and organizes key territorial data in a WebGIS environment. The application allows simple, integrated exploration of fruit and vegetable supply chain dynamics, connections with the local tourism system, and the location of land and crops for territorial analysis.',
      'idx.btn.explore': 'Explore layers',
      'idx.btn.learn': 'Learn more about the platform',
      'idx.numeri.title': 'MOR Closed Market in Numbers',
      'idx.numeri.intro': 'Infographic section dedicated to a concise overview of the closed market, preserving the visual content and integrating it into the new graphic identity of the portal.',
      'idx.features.title': 'Platform Information Layers',
      'idx.features.intro': 'The platform is organized into thematic layers representing territorial datasets. Each layer enables a specific reading of the local system and contributes to an overview of the Roero Fruit and Vegetable Market.',
      'idx.card.photo.title': 'Agri-photovoltaic Layer',
      'idx.card.photo.desc': 'Mapping of available land for territorial analysis related to the location of photovoltaic installations.',
      'idx.card.od.title': 'Origin-Destination Layer',
      'idx.card.od.desc': 'Visualization of historical flows of fruit and vegetable products between municipalities, organized by origin and destination.',
      'idx.card.tourism.title': 'Tourism Layer',
      'idx.card.tourism.desc': 'Identification of areas where the agricultural supply chain intersects with the territory\'s tourism supply chains.',
      'idx.note': 'In this revision, references to the contact section have been removed, in line with the annotations in the content changes PDF.',

      // partners.html
      'par.breadcrumb': 'Home / Partners',
      'par.kicker': 'Our partners',
      'par.title': 'In collaboration with the Politecnico di Torino',

      // explore-MOR.html
      'exp.nav.numbers': 'Numbers',
      'exp.nav.features': 'Layers',
      'exp.breadcrumb': 'Home / Overview',
      'exp.kicker': 'Project Overview',
      'exp.h1': 'MOR: a GIS platform for understanding the territory',
      'exp.lead': 'The MOR platform is a pilot WebGIS application developed to integrate and visualize territorial data relevant to the Roero agri-food system.',
      'exp.support': 'The portal has no evaluative or regulatory purpose, but allows consultation in georeferenced form of datasets useful for supply chain, logistics, and territorial context analysis.',
      'exp.p1': 'Through the layer consultation, it is possible to observe origin-destination flows in the closed market of fruit and vegetable products, based on the 2026 census. The intersection with tourist areas and routes is also represented. With appropriate authorization, exclusion and suitability factors related to the installation of agri-photovoltaic panels can be viewed.',
      'exp.p2': 'The platform is therefore a territorial reading tool: it collects heterogeneous information, makes it navigable on a geographic basis, and enables a concise but structured consultation of the results produced by the project.',
      'exp.layers.title': 'Available Layers',
      'exp.card.photo.title': 'Agri-photovoltaic',
      'exp.card.photo.desc': 'Territorial mapping of surveyed land for location analysis.',
      'exp.card.od.title': 'Origin-Destination',
      'exp.card.od.desc': 'Visualization of historical flows of fruit and vegetable products.',
      'exp.card.tourism.title': 'Tourism Supply Chains',
      'exp.card.tourism.desc': 'Areas of intersection between the agricultural system and the tourism system.',

      // photovoltaic.html
      'pho.breadcrumb': 'Home / Layers / Agri-photovoltaic',
      'pho.h1': 'Agri-photovoltaic Layer',
      'pho.lead': 'Territorial mapping of surveyed land for location analysis.',
      'pho.support': 'This layer collects and displays geographic data related to the elements considered in the project for territorial analysis connected to photovoltaics.',
      'pho.btn.map': '&#128506; Open Photovoltaic Map',
      'pho.p1': 'The consultation allows the surveyed elements to be located and read in the spatial context of the Roero, without making economic, design, or regulatory assessments.',
      'pho.p2': 'The layer was developed as an information component and constitutes a cartographic base useful for subsequent analyses. The final WebGIS output can be accompanied by a brief methodological paragraph describing the selection criteria, the displayed attributes, and any distinction between land, crops, and elements subject to constraints.',
      'pho.note': '<strong>To be completed:</strong> the descriptive section on data and methodology can be refined once you have the definitive list of fields actually published in the map.',

      // tourism.html
      'tou.btn.map': '&#128506; Open Tourism Map',
      'tou.breadcrumb': 'Home / Layers / Tourism supply chains',
      'tou.h1': 'Tourism Supply Chains Layer',
      'tou.lead': 'Areas of intersection between the agricultural system and the tourism system.',
      'tou.support': 'This layer displays the intersection between agricultural supply chain data and any tourism supply chains present in the territory.',
      'tou.p1': 'The objective is to provide a spatial reading of the areas where agricultural production, services, and territorial attractiveness overlap or interact.',
      'tou.p2': 'The layer has an informative and educational function: it allows observation of the territorial distribution of data and supports an integrated reading of the local context within the WebGIS platform.',
      'tou.p3': 'Roero is listed among UNESCO World Heritage sites for its wine-growing landscapes. The content of the tourism layer refers to the municipalities of Roero and the "WineTour tra i cru del Roero" routes, born from the collaboration between the Consorzio di Tutela Roero and the Ecomuseo delle Rocche del Roero. Website: https://www.consorziodelroero.it/i-winetour-tra-i-cru-del-roero/',
      'tou.data.winetour': 'WineTour tra i cru del Roero',
      'tou.data.comuni': 'Municipalities of Roero',
      'tou.data.consorzio': 'Consorzio di Tutela Roero / Ecomuseo delle Rocche del Roero',

      // origin-destination.html
      'od.breadcrumb': 'Home / Layers / Origin-destination',
      'od.h1': 'Origin-Destination Layer',
      'od.lead': 'Visualization of historical flows of fruit and vegetable products.',
      'od.support': 'This layer represents the origin-destination matrix of fruit and vegetable products, built from available historical data.',
      'od.btn.method': '&#8595; Methodology',
      'od.btn.gis': '&#8595; GIS Sources',
      'od.btn.map': '&#128506; Open OD Flow Map',
      'od.p1': 'The visualization allows reading the connections between the source and destination territories of the flows, offering a concise and animated representation of the logistical relationships of the supply chain.',
      'od.p2': 'The layer was developed as an infographic visualization tool, useful for interpreting the spatial organization of product movements in the closed system of the Roero Fruit and Vegetable Market. The data proposed is derived from the census carried out in 2026.',
      'od.p3': 'Each flow record connects a municipality of origin, where the product originates, to the MOR. Records are dated and categorized by product type and producer.',
      'od.method.title': 'Methodology',
      'od.method.p1': 'To analyze the spatial distribution of supply flows within the Roero Fruit and Vegetable Market system, an origin-destination (OD) matrix was constructed to quantify the logistical relationships between producers and the Mercato Ortofrutticolo della Roero (MOR). The first step involved the georeferencing of each producer\'s location within the study area, using coordinate data to accurately position each supply node on the map.',
      'od.method.p2': 'Both the producer locations and the road network were projected under a common coordinate reference system WGS 84 / UTM Zone 32N (EPSG:32632), ensuring geometric consistency and metric accuracy across all spatial layers used in the analysis. The road network covering the study area was subsequently integrated into the spatial model, serving as the basis for route calculation between all identified nodes.',
      'od.method.p3': 'Using QGIS software, the OD matrix was computed for two sets of relationships: producer-to-producer connections, and producer-to-MOR connections. For each origin-destination pair, the shortest road path was calculated and evaluated in terms of distance (km) and estimated transport cost per kilometre, yielding a comprehensive cost-distance matrix. The resulting values are reported in the table below.',
      'od.method.p4': 'To support the interpretation of these spatial flows, an animated cartographic visualization was developed. Each producer\'s movement is represented as a dynamic flow on the map, with interactive pop-up labels displaying the distance associated with each specific route. This animated representation enhances the readability of the OD matrix outputs, allowing users to intuitively trace the spatial organization of product movements from each producer\'s location to the market, and to assess the relative logistical effort involved in each supply relationship.',
      'od.method.p5': 'Each flow record connects a municipality of origin, where the product originates, to the MOR. Records are dated and categorized by product type and producer.',
      'od.data.census': 'MOR closed market census',
      'od.data.road': 'Road Network',
      'od.data.study': 'Study area',

      // webgis-tourism
      'gis.tou.filter.title': 'Layer Filter',
      'gis.tou.filter.hint': 'Click a section to toggle layers',
      'gis.tou.study': 'Study Area',
      'gis.tou.tracks': 'WineTour tra i cru del Roero',
      'gis.tou.market.group': 'Market Location',
      'gis.tou.roero': 'Roero municipalities',
      'gis.tou.cuneo': 'Cuneo Province',
      'gis.tou.asti': 'Asti Province',
      'gis.tou.alessandria': 'Alessandria Province',
      'gis.tou.regione': 'Piedmont Region',
      'gis.tou.track4': 'Route 4',
      'gis.tou.track3': 'Route 3',
      'gis.tou.track2': 'Route 2',
      'gis.tou.track1': 'Route 1',
      'gis.tou.market.name': 'Roero Fruit and Vegetable Market',
      'gis.tou.back': '&#8592; Back',
      'gis.tou.legend.title': 'Legend',
      'gis.tou.legend.empty': 'Select a layer group on the left to see the legend.',

      // webgis-od
      'gis.od.filter.title': 'Layer Filter',
      'gis.od.filter.hint': 'Click a section to toggle layers',
      'gis.od.study': 'Study Area',
      'gis.od.flows': 'Origin-Destination Flows',
      'gis.od.localities': 'Localities',
      'gis.od.roero': 'Roero municipalities',
      'gis.od.cuneo': 'Cuneo Province',
      'gis.od.asti': 'Asti Province',
      'gis.od.alessandria': 'Alessandria Province',
      'gis.od.regione': 'Piedmont Region',
      'gis.od.3pl': '3PL MOR',
      'gis.od.p1': 'Pomodoro Cerrato d\'Asti',
      'gis.od.p2': 'Hazelnuts',
      'gis.od.p3': 'Aubergines',
      'gis.od.p4': 'Bell Peppers',
      'gis.od.p5': 'Traditional Peaches',
      'gis.od.p6': 'Broad Beans',
      'gis.od.p7': 'Madernassa Pears',
      'gis.od.p8': 'Dalmazzine Plums',
      'gis.od.p9': 'Strawberry Grapes',
      'gis.od.p10': 'Fresh Red Grapes',
      'gis.od.p11': 'Pears',
      'gis.od.p12': 'Borlotti Beans',
      'gis.od.p13': 'Materna Pears',
      'gis.od.localit': 'OD Matrix Localities',
      'gis.od.back': '&#8592; Back',
      'gis.od.legend.title': 'Legend',
      'gis.od.legend.empty': 'Select a layer group on the left to see the legend.',

      // webgis-photovoltaic
      'gis.photo.filter.title': 'Layer Filter',
      'gis.photo.filter.hint': 'Click a section to toggle layers',
      'gis.photo.study': 'Study Area',
      'gis.photo.market.group': 'Market Location',
      'gis.photo.exclusion.group': 'Exclusion Factors',
      'gis.photo.photo.group': 'Photovoltaic Suitability',
      'gis.photo.catasto.group': 'Catasto',
      'gis.photo.lcp.group': 'Land Cover',
      'gis.photo.roero': 'Roero municipalities',
      'gis.photo.cuneo': 'Cuneo Province',
      'gis.photo.asti': 'Asti Province',
      'gis.photo.alessandria': 'Alessandria Province',
      'gis.photo.regione': 'Piedmont Region',
      'gis.photo.market.name': 'Roero Fruit and Vegetable Market',
      'gis.photo.natura': 'Natura 2000 Network',
      'gis.photo.aree': 'Protected Areas (EUAP)',
      'gis.photo.frana': 'High Landslide Hazard',
      'gis.photo.idraulica': 'High Hydraulic Hazard',
      'gis.photo.corpi': 'Water Bodies with Buffer',
      'gis.photo.stradale': 'Road Network',
      'gis.photo.ferroviaria': 'Railway Network',
      'gis.photo.slope': 'Slope Analysis',
      'gis.photo.aspect': 'Aspect Analysis',
      'gis.photo.catasto.layer': 'Originali di Impianto',
      'gis.photo.lcp.layer': 'Land Cover Piemonte 2021',
      'gis.photo.suit.none': 'Not suitable',
      'gis.photo.suit.vlow': 'Very low suitability',
      'gis.photo.suit.low': 'Low suitability',
      'gis.photo.suit.mod': 'Moderate suitability',
      'gis.photo.suit.high': 'High suitability',
      'gis.photo.suit.vhigh': 'Very high suitability',
      'gis.photo.back': '&#8592; Back',
      'gis.photo.legend.title': 'Legend',
      'gis.photo.legend.empty': 'Select a layer group on the left to see the legend.',
    }
  };

  function setLang(lang) {
    localStorage.setItem('mor-lang', lang);
    document.documentElement.lang = lang;
    var els = document.querySelectorAll('[data-i18n]');
    for (var i = 0; i < els.length; i++) {
      var key = els[i].getAttribute('data-i18n');
      if (T[lang] && T[lang][key] !== undefined) {
        els[i].innerHTML = T[lang][key];
      }
    }
    document.querySelectorAll('.lang-btn[data-lang]').forEach(function (btn) {
      btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
    });
  }

  window.setLang = setLang;

  document.addEventListener('DOMContentLoaded', function () {
    var saved = localStorage.getItem('mor-lang') || 'it';
    setLang(saved);
  });
})();
